Metrics/MethodLength:
    Max: 20

Style/NegatedIf:
    Enabled: false

Style/HashSyntax:
  EnforcedStyle: ruby19

Style/IfUnlessModifier:
    Enabled: false

Style/Next:
    Enabled: false

Lint/UselessAssignment:
  AutoCorrect: false

Style/GuardClause:
    Enabled: false
